name: Node.js CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Show Node.js version
        run: node --version && npm --version
        
      - name: Show directory structure
        run: ls -la
        
      - name: Run lint
        run: npm run lint
        
      - name: Run tests with verbose output
        run: npm test -- --verbose
        env:
          NODE_ENV: unittest
          
      - name: Build
        run: npm run build
